- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ubuntu
  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: apache2
      state: latest
  - name: write the apache config file
    template:
      src: templates/apache2.conf.j2
      dest: /etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: apache2
      state: started
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

