---

- name: "mariadb-server installation"
  apt:
    name:  "mariadb-server"
    state: "installed"

- name: "start mariadb service"
  service:
    name:  "mariadb"
    state: "started"
    enabled: yes
