---
- name: Add MongoDB PPA key
  apt_key:
    id: "{{ mongodb_ubuntu_apt_key }}"
    keyserver: "keyserver.ubuntu.com"
  become: true
  become_user: root

- name: Add MongoDB PPA
  apt_repository:
    repo: >
      deb
      https://repo.mongodb.org/apt/ubuntu
      {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }}
      multiverse
    update_cache: true
  become: true
  become_user: root

- name: Install MongoDB package
  apt:
    name: mongodb-org
    force_apt_get: true
  notify:
    - Restart MongoDB
  become: true
  become_user: root

- name: Create MongoDB data directory
  file:
    path: "{{ mongodb_data_path }}"
    owner: mongodb
    group: mongodb
    state: directory
    recurse: true
  notify:
    - Restart MongoDB
  become: true
  become_user: root

- name: Install MongoDB configuration
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify:
    - Restart MongoDB
  become: true
  become_user: root

- name: Enable MongoDB service
  service:
    name: mongod
    enabled: true
  become: true
  become_user: root
